package com.ncda.entity;

import java.util.Date;

public class AccountBillUploadRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.ID
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.YEAR_MONTH
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    private Date yearMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    private String fileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.ID
     *
     * @return the value of account_bill_upload_record.ID
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.ID
     *
     * @param id the value for account_bill_upload_record.ID
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.YEAR_MONTH
     *
     * @return the value of account_bill_upload_record.YEAR_MONTH
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    public Date getYearMonth() {
        return yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.YEAR_MONTH
     *
     * @param yearMonth the value for account_bill_upload_record.YEAR_MONTH
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    public void setYearMonth(Date yearMonth) {
        this.yearMonth = yearMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.FILE_CONTENT
     *
     * @return the value of account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    public String getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.FILE_CONTENT
     *
     * @param fileContent the value for account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    public void setFileContent(String fileContent) {
        this.fileContent = fileContent;
    }
}