package com.ncda.entity;

public class AccountBillType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.TYPE_ID
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.TYPE_ONE_NAME
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    private String typeOneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.USER_ID
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.TYPE_KEYWORD
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    private String typeKeyword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.TYPE_ID
     *
     * @return the value of account_bill_type.TYPE_ID
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.TYPE_ID
     *
     * @param typeId the value for account_bill_type.TYPE_ID
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.TYPE_ONE_NAME
     *
     * @return the value of account_bill_type.TYPE_ONE_NAME
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public String getTypeOneName() {
        return typeOneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.TYPE_ONE_NAME
     *
     * @param typeOneName the value for account_bill_type.TYPE_ONE_NAME
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public void setTypeOneName(String typeOneName) {
        this.typeOneName = typeOneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.USER_ID
     *
     * @return the value of account_bill_type.USER_ID
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.USER_ID
     *
     * @param userId the value for account_bill_type.USER_ID
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.TYPE_KEYWORD
     *
     * @return the value of account_bill_type.TYPE_KEYWORD
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public String getTypeKeyword() {
        return typeKeyword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.TYPE_KEYWORD
     *
     * @param typeKeyword the value for account_bill_type.TYPE_KEYWORD
     *
     * @mbggenerated Tue Aug 31 15:21:51 CST 2021
     */
    public void setTypeKeyword(String typeKeyword) {
        this.typeKeyword = typeKeyword;
    }
}