package com.ncda.entity;

import java.util.Date;

public class AccountBillUploadRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.ID
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.DATE
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.DEL_STATE
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    private String delState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.UPLOAD_TIME
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    private String fileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.ID
     *
     * @return the value of account_bill_upload_record.ID
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.ID
     *
     * @param id the value for account_bill_upload_record.ID
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.DATE
     *
     * @return the value of account_bill_upload_record.DATE
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.DATE
     *
     * @param date the value for account_bill_upload_record.DATE
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.DEL_STATE
     *
     * @return the value of account_bill_upload_record.DEL_STATE
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public String getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.DEL_STATE
     *
     * @param delState the value for account_bill_upload_record.DEL_STATE
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public void setDelState(String delState) {
        this.delState = delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.UPLOAD_TIME
     *
     * @return the value of account_bill_upload_record.UPLOAD_TIME
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.UPLOAD_TIME
     *
     * @param uploadTime the value for account_bill_upload_record.UPLOAD_TIME
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.FILE_CONTENT
     *
     * @return the value of account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public String getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.FILE_CONTENT
     *
     * @param fileContent the value for account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Tue Aug 17 14:27:59 CST 2021
     */
    public void setFileContent(String fileContent) {
        this.fileContent = fileContent;
    }
}