package com.ncda.entity;

import java.util.Date;

public class AccountBillUploadRecord {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.ID
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.DATE
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    private Date date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    private String fileContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.ID
     *
     * @return the value of account_bill_upload_record.ID
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.ID
     *
     * @param id the value for account_bill_upload_record.ID
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.DATE
     *
     * @return the value of account_bill_upload_record.DATE
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.DATE
     *
     * @param date the value for account_bill_upload_record.DATE
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_upload_record.FILE_CONTENT
     *
     * @return the value of account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    public String getFileContent() {
        return fileContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_upload_record.FILE_CONTENT
     *
     * @param fileContent the value for account_bill_upload_record.FILE_CONTENT
     *
     * @mbggenerated Mon Aug 16 14:39:13 CST 2021
     */
    public void setFileContent(String fileContent) {
        this.fileContent = fileContent;
    }
}