package com.ncda.entity;

public class AccountBillType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.TYPE_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    private Integer typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.TYPE_ONE_NAME
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    private String typeOneName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.PARENT_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.TYPE_TWO_NAME
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    private String typeTwoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column account_bill_type.USER_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.TYPE_ID
     *
     * @return the value of account_bill_type.TYPE_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public Integer getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.TYPE_ID
     *
     * @param typeId the value for account_bill_type.TYPE_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public void setTypeId(Integer typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.TYPE_ONE_NAME
     *
     * @return the value of account_bill_type.TYPE_ONE_NAME
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public String getTypeOneName() {
        return typeOneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.TYPE_ONE_NAME
     *
     * @param typeOneName the value for account_bill_type.TYPE_ONE_NAME
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public void setTypeOneName(String typeOneName) {
        this.typeOneName = typeOneName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.PARENT_ID
     *
     * @return the value of account_bill_type.PARENT_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.PARENT_ID
     *
     * @param parentId the value for account_bill_type.PARENT_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.TYPE_TWO_NAME
     *
     * @return the value of account_bill_type.TYPE_TWO_NAME
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public String getTypeTwoName() {
        return typeTwoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.TYPE_TWO_NAME
     *
     * @param typeTwoName the value for account_bill_type.TYPE_TWO_NAME
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public void setTypeTwoName(String typeTwoName) {
        this.typeTwoName = typeTwoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column account_bill_type.USER_ID
     *
     * @return the value of account_bill_type.USER_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column account_bill_type.USER_ID
     *
     * @param userId the value for account_bill_type.USER_ID
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}