package com.ncda.entity;

import java.util.Date;

public class TodoList {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.ID
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.CONTENT
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.STATUS
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private Boolean status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.CREATE_TIME
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.COMPLETE_TIME
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private Date completeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.USER_ID
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column todo_list.DEL_STATE
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    private Boolean delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.ID
     *
     * @return the value of todo_list.ID
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.ID
     *
     * @param id the value for todo_list.ID
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.CONTENT
     *
     * @return the value of todo_list.CONTENT
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.CONTENT
     *
     * @param content the value for todo_list.CONTENT
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.STATUS
     *
     * @return the value of todo_list.STATUS
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.STATUS
     *
     * @param status the value for todo_list.STATUS
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.CREATE_TIME
     *
     * @return the value of todo_list.CREATE_TIME
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.CREATE_TIME
     *
     * @param createTime the value for todo_list.CREATE_TIME
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.COMPLETE_TIME
     *
     * @return the value of todo_list.COMPLETE_TIME
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public Date getCompleteTime() {
        return completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.COMPLETE_TIME
     *
     * @param completeTime the value for todo_list.COMPLETE_TIME
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setCompleteTime(Date completeTime) {
        this.completeTime = completeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.USER_ID
     *
     * @return the value of todo_list.USER_ID
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.USER_ID
     *
     * @param userId the value for todo_list.USER_ID
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column todo_list.DEL_STATE
     *
     * @return the value of todo_list.DEL_STATE
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public Boolean getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column todo_list.DEL_STATE
     *
     * @param delState the value for todo_list.DEL_STATE
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    public void setDelState(Boolean delState) {
        this.delState = delState;
    }
}