package com.ncda.dao;

import com.ncda.entity.AccountBillUploadRecord;

public interface AccountBillUploadRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    int insert(AccountBillUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    int insertSelective(AccountBillUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    AccountBillUploadRecord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    int updateByPrimaryKeySelective(AccountBillUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(AccountBillUploadRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_upload_record
     *
     * @mbggenerated Fri Aug 13 09:17:25 CST 2021
     */
    int updateByPrimaryKey(AccountBillUploadRecord record);
}