package com.ncda.dao;

import com.ncda.entity.AccountBillType;

public interface AccountBillTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_type
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    int deleteByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_type
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    int insert(AccountBillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_type
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    int insertSelective(AccountBillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_type
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    AccountBillType selectByPrimaryKey(Integer typeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_type
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    int updateByPrimaryKeySelective(AccountBillType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill_type
     *
     * @mbggenerated Fri Aug 20 17:07:52 CST 2021
     */
    int updateByPrimaryKey(AccountBillType record);
}