package com.ncda.dao;

import com.ncda.entity.AccountBill;

public interface AccountBillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill
     *
     * @mbggenerated Fri Aug 13 09:16:33 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill
     *
     * @mbggenerated Fri Aug 13 09:16:33 CST 2021
     */
    int insert(AccountBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill
     *
     * @mbggenerated Fri Aug 13 09:16:33 CST 2021
     */
    int insertSelective(AccountBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill
     *
     * @mbggenerated Fri Aug 13 09:16:33 CST 2021
     */
    AccountBill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill
     *
     * @mbggenerated Fri Aug 13 09:16:33 CST 2021
     */
    int updateByPrimaryKeySelective(AccountBill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_bill
     *
     * @mbggenerated Fri Aug 13 09:16:33 CST 2021
     */
    int updateByPrimaryKey(AccountBill record);

}