package com.ncda.dao;

import com.ncda.entity.TodoList;

public interface TodoListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    int insert(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    int insertSelective(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    TodoList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    int updateByPrimaryKeySelective(TodoList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table todo_list
     *
     * @mbggenerated Thu Sep 09 16:28:57 CST 2021
     */
    int updateByPrimaryKey(TodoList record);
}