spring:
  profiles:
    active: dev02
  redis:
    host: localhost
    port: 6379
    database: 0
mybatis:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml
  type-aliases-package: com.ncda.entity
logging:
  level:
    com:
      ncda: DEBUG